# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-20 02:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_friend_current_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post',
        ),
        migrations.AddField(
            model_name='post',
            name='picture',
            field=models.ImageField(default=1, upload_to=b'pictures'),
            preserve_default=False,
        ),
    ]
