# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-20 03:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20180320_0252'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
