# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-09 02:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='post',
        ),
        migrations.AddField(
            model_name='tag',
            name='post',
            field=models.ManyToManyField(null=True, to='home.Post'),
        ),
    ]
