# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-17 05:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20180409_0246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='approved',
        ),
        migrations.AddField(
            model_name='tag',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
