# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-26 00:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20180417_0503'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='bluredPicture',
            field=models.ImageField(null=True, upload_to=b''),
        ),
    ]
