# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-26 00:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_post_bluredpicture'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='bottom',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='left',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='right',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='top',
            field=models.IntegerField(null=True),
        ),
    ]
