# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-30 06:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20180426_0046'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='labels',
            field=models.TextField(null=True),
        ),
    ]
