# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-30 06:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_post_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='lat',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='lon',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
