# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-30 06:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20180630_0628'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
