# Generated by Django 2.0 on 2019-01-10 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pig', '0007_liuyi_test_filed'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Liuyi',
            new_name='Liuyi_test',
        ),
    ]
