# Generated by Django 2.0 on 2019-01-10 19:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pig', '0009_auto_20190110_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='depart_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 10, 19, 14, 29, 38342, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='ride',
            name='isStudent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='album',
            name='album_logo',
            field=models.CharField(max_length=100),
        ),
    ]
