# Generated by Django 2.0 on 2019-01-10 19:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pig', '0017_auto_20190110_1321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='depart_date',
        ),
        migrations.AlterField(
            model_name='ride',
            name='add_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 10, 19, 21, 53, 703910, tzinfo=utc)),
        ),
    ]
