# Generated by Django 2.0 on 2019-01-10 19:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pig', '0021_auto_20190110_1323'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ride',
            old_name='wechat_name',
            new_name='wechat',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='wechat_number',
        ),
        migrations.AlterField(
            model_name='ride',
            name='add_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 10, 19, 25, 48, 31992, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ride',
            name='total_seats',
            field=models.IntegerField(default=3),
        ),
    ]
