# Generated by Django 2.0 on 2019-01-16 02:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pig', '0024_auto_20190115_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='Add_Date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 16, 2, 45, 45, 159043, tzinfo=utc)),
        ),
    ]
