# Generated by Django 2.0 on 2019-02-04 00:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pig', '0027_auto_20190115_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='Add_Date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 4, 0, 51, 6, 184925, tzinfo=utc)),
        ),
    ]
