# Generated by Django 2.0 on 2019-02-06 05:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pig', '0029_auto_20190205_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='Gad_Need',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='ride',
            name='Add_Date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 6, 5, 40, 13, 928418, tzinfo=utc)),
        ),
    ]
