# Generated by Django 2.0 on 2019-02-06 05:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pig', '0031_auto_20190205_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='askride',
            name='From_City',
            field=models.CharField(default='College Station', max_length=200),
        ),
        migrations.AddField(
            model_name='askride',
            name='To_City',
            field=models.CharField(default='Houston', max_length=200),
        ),
        migrations.AlterField(
            model_name='askride',
            name='Gas_Return',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='ride',
            name='Add_Date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 6, 5, 52, 4, 589531, tzinfo=utc)),
        ),
    ]
