# Generated by Django 2.0 on 2019-02-06 05:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pig', '0032_auto_20190205_2352'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ride',
            old_name='Gad_Need',
            new_name='Gas_Need',
        ),
        migrations.AlterField(
            model_name='ride',
            name='Add_Date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 6, 5, 58, 10, 502023, tzinfo=utc)),
        ),
    ]
