# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-25 20:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20180325_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='face',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
